In [ ]:
import tensorflow as tf

tensor = tf.constant([[1,2,3],[4,5,6]])
rank = tf.ransk(tensor)
shape = tf.shape(tensor)
size = tf.size(tensor)
print("TENSOR", tensor)
print("")
print("")
print("")
print("TENSOR SHAPE", shape)
print("")
print("")
print("")
print("TENSOR SIZE", size)
print("")
print("")
print("")
print("TENSOR RANK", rank)

TENSOR tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)



TENSOR SHAPE tf.Tensor([2 3], shape=(2,), dtype=int32)



TENSOR SIZE tf.Tensor(6, shape=(), dtype=int32)


In [1]:
import tensorflow as tf
t1 = tf.constant([0,1,2,3,4,5,6,7,8])
t1

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [6]:

s1 = tf.slice(t1, begin=[4], size=[3])
print(s1)


tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [9]:
s1 = t1[0:5]
print(s1)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [13]:
t2 = tf.constant([[0,1,2],[3,4,5],[6,7,8]])
t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [17]:
first_row = tf.slice(t2, [0,0] , [1, tf.shape(t2)[1]])
print("FIRST ROW",first_row)

FIRST ROW tf.Tensor([[0 1 2]], shape=(1, 3), dtype=int32)


In [24]:
second_column = tf.slice(t2, [0,1], [tf.shape(t2)[0], 1])
second_column

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [4],
       [7]], dtype=int32)>

In [33]:
second_and_third_columns = tf.slice(t2, [0,1], [tf.shape(t2)[0], 2])
second_and_third_columns

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [34]:
t3 = tf.constant([0,1,2,3,4,5,6,7,8])
t3

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [46]:
t3 = tf.constant([0,1,2,3,4,5,6,7,8])

Indices = [[1,1,1], [0,0,0], [1,0,3]]
special_picks = tf.gather_nd(t3, indices=[[1], [0], [3]])
print(special_picks)

tf.Tensor([1 0 3], shape=(3,), dtype=int32)


In [37]:
Index = [[1], [3], [5], [7]]
values = [10, 20, 30, 50]

t4 = tf.scatter_nd(indices= Index, updates = values, shape = [8])
t4

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 0, 10,  0, 20,  0, 30,  0, 50], dtype=int32)>

In [38]:
t5 = tf.zeros(shape = (4,5))
t5

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [42]:
Index = [[0,0],
         [1,1],
         [2,2],
         [3,3]]

values = [100, 200, 300, 400]
t6 = tf.scatter_nd(indices = Index,
                   updates = values,
                   shape = t5.shape)
print(t6)

tf.Tensor(
[[100   0   0   0   0]
 [  0 200   0   0   0]
 [  0   0 300   0   0]
 [  0   0   0 400   0]], shape=(4, 5), dtype=int32)


In [3]:
import tensorflow as tf
t = tf.constant([[1,2,3],
                [4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
result = tf.reshape(t, [-1])
print("The result is :\n",result)
print('\n Original Tensor Shape:',tf.shape(t))  
print('Flattened Tensor Shape:',tf.shape(result))  

The result is :
 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)

 Original Tensor Shape: tf.Tensor([2 3], shape=(2,), dtype=int32)
Flattened Tensor Shape: tf.Tensor([6], shape=(1,), dtype=int32)
